### ISSUE TITLE
doesnt work with FQDN

### ISSUE THREAD

**Issue by pansa** [jvns/dns-lookup#1]
service does not work with domain as FQDN

**Comment by BlackthornYugen** [comment]
It seems to work with FQDNs for me. Is this bug about it not working with a trailing dot? 

https://dns-lookup.jvns.ca/#dns-lookup.jvns.ca.|all-the-records
![image](https://user-images.githubusercontent.com/3138467/109686717-868e3980-7b50-11eb-9790-9dbd090f6cbb.png)

**Comment by pansa** [comment]
It is not a trailing dot, this is root domain :)  
"dns-lookup.jjvns.ca." - is exacly FQDN form. So, yes, at the moment this form is not working.

**Comment by jvns** [comment]
Thanks, fixed in https://github.com/jvns/dns-lookup/commit/bade4bf077bd0a31b65d6ed363e979e9cd6979f1
