### ISSUE TITLE
SPF records please 🙏🏻

### ISSUE THREAD

**Issue by todrobbins** [jvns/dns-lookup#7]
I'd love to get SPF records back if possible.

Thanks for the rad tool!

**Comment by jvns** [comment]
hey @todrobbins, thanks for your interest! SPF records are a kind of `TXT` record so you can look up SPF records by looking up TXT records

It doesn't do any SPF-specific checks (like validating that they have the correct format) though if that's what you're asking for -- I'm unlikely to build that and I think something like [mxtoolbox](https://mxtoolbox.com/NetworkTools.aspx) would probably be a better fit for that

let me know if that helps or if I'm misunderstanding your request!

**Comment by todrobbins** [comment]
That makes sense! I was thinking more like what mxtoolbox does, so I'll close this issue. Thanks again!
